### ISSUE TITLE
Docs on magnetometer?

### ISSUE THREAD

**Issue by mkarliner** [emfcamp/tidal-docs#11]
I'm probably missing something, but I can't find any details of how to 
access the magnetometer.

**Comment by tomsci** [comment]
There aren't any docs (yet) but there is example code here: https://github.com/emfcamp/TiDAL-Firmware/blob/main/modules/magnet_app/__init__.py

Basically:

```python
import magnetometer
(x, y, z) = magnetometer.get_xyz()
```

That gets you only the raw data, you'll probably have to apply some smoothing.

**Comment by mkarliner** [comment]
Great.thanks
