### ISSUE TITLE
Screen replacement source

### ISSUE THREAD

**Issue by Snuggle** [emfcamp/tidal-docs#17]
Hello!

Could I please ask what the name/model is used for the screen? I’d like to add how to purchase replacements to https://github.com/emfcamp/tidal-docs/blob/main/screenreplacementguide.md

**Comment by kliment** [comment]
Yes, of course. The screen we use is the LHS114TM-IG01 from Limito Technology

It's available to buy from https://www.buydisplay.com/1-14-inch-tft-lcd-display-ips-panel-screen-135x240-for-smart-watch and https://www.ebay.co.uk/itm/293392674769 is reportedly the same product.
