### ISSUE TITLE
How I got programming to work

### ISSUE THREAD

**Issue by 0xToby** [emfcamp/tidal-docs#8]
Hey I couldn't get the web interface to work nicely. It kept hanging when saving code, so I worked out an alternative way. Since it just talks to the python console on serial I made a Python script to copy a single file. This way, you can write code to a local file and upload that easily.
Uploader script (upload.py):

```
import sys, serial

appname = sys.argv[1]
filename = sys.argv[2]

print("loading file %s as app %s"%(filename, appname))

filedata = open(filename, "rb").read()
ser = serial.Serial('COM6')

ser.write(b"""fo = open("/apps/%s/__init__.py", "wb")\r\n"""%appname.encode())
ser.write(b"fo.write(\"\"\""+filedata+b"\"\"\")\r\n")
ser.write(b"fo.close()\r\n")
```

To use it, do this:

1. Use the normal web interface to make a new app (don't use spaces or special characters). Then click disconnect on the web interface (keep the badge plugged in though!)
2. Copy this upload.py script to a folder on your computer
3. Install pyserial ( `python3 -m pip install pyserial` ) if you haven't already
4. Write some code on your computer (I put it in the file app.py)
5. Run the upload.py file to copy app.py to the badge: `python3 upload.py Test app.py` will replace the code for the app called "Test" with the code in the file "app.py"
6. You might have to reboot your badge first, but you should be able to select it from the menu and run it :)
7. GOTO 4, make something cool :)

**Comment by tomsci** [comment]
Good hacking 👍 

There is however already a script available to do this called pyboard.py, which is available in one of the submodules of TiDAL-Firmware and is described here: https://github.com/emfcamp/tidal-docs/blob/main/AppQuickstart.md#repl

Direct link is here:
https://github.com/micropython/micropython/blob/master/tools/pyboard.py
